### ISSUE TITLE
External Stream query format different from stream

### ISSUE THREAD

**Issue by leo-cai-timeplus** [timeplus-io/proton#334]
**Describe what's wrong**

```sql
CREATE EXTERNAL STREAM test (name string) SETTINGS type='kafka', brokers='ckafka-wd4vnq42.ap-shanghai.ckafka.tencentcloudmq.com:50002',topic='test',security_protocol='SASL_PLAINTEXT',username='ckafka-wd4vnq42#user',password='3#ee4$rr';

insert into test(name) values('a')('b')('c');
```
```
a4d6fe58f045 :) select name from test format JSONEachRow

SELECT 
  name
FROM 
  test
FORMAT JSONEachRow

Query id: 537f5b1b-3ea5-43ee-bdc8-1c2eb1b45d2d

{"name":"{\"name\":\"a\"}\n{\"name\":\"b\"}\n{\"name\":\"c\"}\n"}
↙ Progress: 1.00 rows, 48.00 B (0.03 rows/s., 1.21 B/s.)                                                                                                                                                                                                    (0.0 CPU)^Cancelling query.
Query was cancelled.

1 row in set. Elapsed: 39.880 sec. 

a4d6fe58f045 :) select name from test

SELECT 
  name
FROM 
  test

Query id: cd7c6651-bb96-4712-ac08-93397677e0b0

┌─name─────────────────────────────────┐
│ {"name":"a"}
{"name":"b"}
{"name":"c"}
 │
└──────────────────────────────────────┘
```
what we expect is like 
```
CREATE EXTERNAL STREAM test_2 (x int, name string) SETTINGS type='kafka', brokers='ckafka-wd4vnq42.ap-shanghai.ckafka.tencentcloudmq.com:50002',topic='test',security_protocol='SASL_PLAINTEXT',username='ckafka-wd4vnq42#user',password='3#ee4$rr',data_format='JSONEachRow';
 insert into test_2(x, name) values (1,'a')(2,'b')(3,'c');

select name from test_2;

SELECT 
  name
FROM 
  test_2

Query id: 3a062d8a-cfa4-4e48-859f-12a1fafefc71

┌─name─┐
│ a    │
│ b    │
│ c    │
└──────┘
```
**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

**Comment by leo-cai-timeplus** [comment]
```sql
CREATE EXTERNAL STREAM test (name string) SETTINGS type='kafka', brokers='ckafka-wd4vnq42.ap-shanghai.ckafka.tencentcloudmq.com:50002',topic='test',security_protocol='SASL_PLAINTEXT',username='ckafka-wd4vnq42#user',password='3#ee4$rr',data_format = 'JSONEachRow';
```
this works as expected;

**Comment by zliang-min** [comment]
This is not a bug.

First, the `test` stream uses the `raw` data format (because `data_format` is not specified). So, when you ran
```sql
insert into test(name) values('a')('b')('c');
```
What were sent to the Kafka topic were
```
{"name": "a"}
{"name": "b"}
{"name": "c"}
```
This is exactly what `select name from test` returned. This is the expected behavior.

Then, when you ran `select name from test format JSONEachRow`, you asked proton to run the query and return the query results as JSON objects, and each row is wrapped in one object. Because the insert above only sent one message to the kafka topic, that means there was only one row. So the result should be `{"name": "<the message in kafka topic>"}` whereas that `<the message in kafka topic>` is the message showed above. And this matches the result you got exactly.

The key to understand this behavior is that an external stream always has its own `data_format`, and if it's not specified, it's `raw`. Using `FORMAT xxx` means you want to format the query results, and the query results from an external stream are already formated.

Please let me know if you still have questions.
