### ISSUE TITLE
No embedded config files after stripping proton binary

### ISSUE THREAD

**Issue by tingfirst** [timeplus-io/proton#459]
**Describe what's wrong**
After stripping proton binary in ARM/Apple Silicon,  there is no default embedded config file.  Proton can't run correctly

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

**Comment by yokofly** [comment]
will take a look later 


for macOS user, can  directly use homebrew to get latest proton  or  use below oneline

## manual install
curl -sSf https://raw.githubusercontent.com/timeplus-io/proton/develop/install.sh | sh

## brew
brew tap timeplus-io/timeplus
brew install proton

**Comment by yokofly** [comment]
Thanks, can be easily reproduced. 

the problem is:
we use llvm toolchain and recommend using `llvm-strip`, instead of the default `strip`(which is held by the **XCode**)
you can verify this by typing `which llvm-strip` and `strip --version` in the macOS terminal

strip/llvm-strip will remove the debug info, making the binary size smaller, but not fitting for problem tracking. 

also, the clickhouse binary is only about 80M, this is because it is compressed. the first time you start up clickhouse binary, you need to wait sometime to uncompress. But I also wanna introduce this feature.
