### ISSUE TITLE
`table` function does not work with external streams

### ISSUE THREAD

**Issue by zliang-min** [timeplus-io/proton#592]
**Describe what's wrong**

Given an kafka external stream `ex_stream`, running `SELECT * FROM table(ex_stream)` never stops. In fact, it behaves exactly the same as `SELECT * FROM ex_stream`, the `table` function is not working in this case.

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

**Comment by jovezhong** [comment]
Our internal discussion lean to enhance the table(..) function to support external stream, just to list all existing data in the topic (from earliest offset)

**Comment by sarwarbhuiyan** [comment]
+1

No matter what is needed to happen inside, the UX should be consistent. Otherwise, it's best to call external streams something else. A stream is a stream so the functions should work more or less the same. Otherwise, the user is left scratching their head and having to keep track of these various limitations.

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
