### ISSUE TITLE
Latency of tumble window

### ISSUE THREAD

**Issue by xwzhu** [timeplus-io/proton#644]
I was playing around with the Market Data example of BTC on the demo cloud by adding a timestamp to the generated bars.
```
SELECT
  window_end,
  earliest(price) AS open,
  latest(price) AS close,
  max(price) AS high,
  min(price) AS low,
  now64() as update_time
FROM
  tumble(mv_coinbase_tickers_extracted, 10s)
GROUP BY
  window_end
```
Here `window_end` is the bar time and `update_time` should be the actual bar generation time. For demo purpose I choose a ten-second window, but the findings applies to longer tumble window as well.

I noticed that there is a consistent latency (400 to 600ms in my case) to every bar generated, please see below. For market data applications such latency may not be acceptable, I wonder is there a way to reduce it?

![bar](https://github.com/timeplus-io/proton/assets/1531640/e7079e74-c2c3-47ef-9ab5-785ea8e5d712)

**Comment by yl-lisen** [comment]
in fact, here the tumble function is based on `_tp_time` (if no specified, it's equal to ingest time of events).
`tumble(<stream>[, <timestamp_col = _tp_time>], <window_interval>)`

May you provide the definition of the `mv_coinbase_tickers_extracted` and the frequency of mv result insertion?
@xwzhu

**Comment by xwzhu** [comment]
@yl-lisen thanks for the quick reply. My example is taken from the following materialized view on the demo cloud:
https://demo.timeplus.cloud/marketdata/console/mviews

As far as I can tell the data frequency for BTC is very high.

**Comment by yl-lisen** [comment]
@xwzhu I cannot access this link, could you have a copy here ?

**Comment by xwzhu** [comment]
Unfortunately no, I did all the experiment online... But I think this is a public page? It is created by people from Timeplus and is the landing page if you create a free account.

**Comment by jovezhong** [comment]
Hi @xwzhu , thanks for reporting this. Because we are using a free coinbase websocket datasource in the example, so the data latency is subsecond but not single digit ms. This can be confirmed by comparing the `time` in the JSON payload vs _tp_time(when the data is ingested)
```sql
select _tp_time,to_time(raw:time) as eventTime,date_diff('ms',eventTime,_tp_time) 
from coinbase_tickers
```
<img width="967" alt="image" src="https://github.com/timeplus-io/proton/assets/5076438/a262408e-ff1c-4ccd-a408-1164ad6a8fc6">

If you purchase level1/level2 high quality data sources, you get lower latency for the data processing.

**Comment by xwzhu** [comment]
@jovezhong Hi Jove, thanks for the reply. Now I modified the query a bit based on yours:

```
WITH parsed_ticks AS (
SELECT
  _tp_time,
  to_time(raw:time) AS event_time,
  date_diff('ms', event_time, _tp_time) AS latency
FROM coinbase_tickers
)
SELECT
  window_end,
  avg(latency) AS receipt_latency,
  now64() AS tumble_gen_time,
  date_diff('ms', window_end, tumble_gen_time) AS tumble_gen_latency
FROM
  tumble(parsed_ticks, 10s)
GROUP BY
  window_end
```

Do you think I am doing correctly to the measure the latency between the tumble window end time and the actual aggregation record generation time? If so, the latency seems even worse and less stable?

![tumble](https://github.com/timeplus-io/proton/assets/1531640/042b72e6-cbdb-4da9-91a2-927047ff4050)

**Comment by xwzhu** [comment]
Tried the following `RANDOM STREAM` locally on my laptop which has a very low latency though, so I am unsure what is causing high latency figures on the cloud. Could it be because of high load?

```
CREATE RANDOM STREAM devices(
  device string default 'device'||to_string(rand()%4), 
  location string default 'city'||to_string(rand()%10),
  temperature float default rand()%1000/10);
```

```
SELECT
  window_end,
  avg(temperature) AS temp,
  now64() as tumble_gen_time,
  date_diff('ms', window_end, tumble_gen_time) AS tumble_latency
FROM
  tumble(devices, 10s)
GROUP BY
  window_end
```

**Comment by jovezhong** [comment]
Hi @xwzhu , thanks for trying the random stream to verify the latency on your laptop. 👍 It's indeed a great way to check the low latency in the idle case. The random stream is sort of a "perfect stream". Data keeps coming continuously and no out of order, no latency between the event time and ingest time. I guess you can get single digit millisecond latency in your laptop.

Now back to the coinbase market data. Since we want everyone can check the demo application and copy it in own workspace, we are using a free websocket address without authentication `wss://ws-feed.exchange.coinbase.com` https://docs.cloud.coinbase.com/exchange/docs/websocket-overview To build latency sensitive app, according to https://docs.cloud.coinbase.com/exchange/docs/fix-msg-market-data, "Exchange FIX Market Data Messages 5.0" with level 3 data is recommended.

As you see with SQL
```sql
SELECT  _tp_time,  to_time(raw:time) AS event_time,
  date_diff('ms', event_time, _tp_time) AS latency
  FROM coinbase_tickers
```
The latency between the event time and ingest time can be anything between 0.1 sec to 1 sec
<img width="674" alt="image" src="https://github.com/timeplus-io/proton/assets/5076438/e5287f2f-dd64-4149-b755-245d510a05b9">

If I virtualize it
<img width="877" alt="image" src="https://github.com/timeplus-io/proton/assets/5076438/17aa7b15-ae69-4e43-b1da-da36350dfa75">
the pink event time has a "shadow" , _tp_time, which can be 0.1-1 sec delay

Now come to an interesting point, how the tumble window is started/triggered.

By default, as a common practice in data streaming space, Timeplus triggers via event time, not wall clock time(aka process time), and it's based on watermark(to support out of order events) There are some docs&blog about this topic ( https://docs.timeplus.com/query-syntax#emit, https://www.timeplus.com/post/top-10-streaming-sql-patterns ) But in short, for streaming data, we expect it is a stream of data, new events keep coming. The next event out of the window will update the watermark and close the prior window

So if you use `tumble(stream,_tp_time, 10s)`, Timeplus will check the _tp_time for each event. When it sees a event out of the 10s window, it will think "okay, I don't need to wait for any other event in previous window. Let me close the previous window and start a new window"
<img width="869" alt="image" src="https://github.com/timeplus-io/proton/assets/5076438/c9a1ec0c-c24d-42b6-a161-7f4679a76de3">

So if there are not a lot of events coming, you get an event at 00:00:12.000, this will trigger the window close for 00:00:00.000 to 00:00:10.000. This extra 2 seconds is the gap between `window_end` with `now64()`

I ran `SELECT  _tp_time,date_diff('ms', lag(_tp_time), _tp_time) AS latency FROM coinbase_tickers` and got a few 1000, 1001, 2000.. Meaning every 1 or 2 seconds there are a new event.

Okay, let's sum up all potential latencies:
* the free coinbase websocket can introduce 100 to 1000 ms for the event time vs ingest time
* in the 10s window, data comes every 1 or 2 seconds. Because of how window close is triggered, the new event will close the previous window. This will add 1000 to 2000 ms
* once the window close signal is captured, Timeplus will do some aggregation and emit the result. This is not zero ms but very fast

That's probably why if you compare the now64() with the window_end, there could be a few hundreds or thousands millisecond delay. If you apply the tumble window on _tp_time, then comparing now64() with the event time, even more gap.

However, if you use a paid market data data source, with low latency between event time and ingest time (say only few ms when you get the data via websocket or tcp), AND if there are high frequent data, then tumble window aggregation will be as good as the random stream. Since new events keep pushing the watermark moving, to close the prior window as soon as possible. Some of our customers in the fintech space did get single digit millisecond realtime metrics with high quality data source and Timeplus.

Sorry the answer is a bit long. There are some advanced settings in Timeplus to calculate via process time (not event time), or set a timeout if we don't see new event coming. Happy to discuss more here, in our community slack, or contact our sales.

**Comment by xwzhu** [comment]
Hi @jovezhong , thanks for the great answer. It explains all my questions, and indeed with perfect random stream my latency is around 1~4 ms.

Closing the issue :)

**Comment by gangtao** [comment]
Thanks @xwzhu @jovezhong , great discussion!
