### ISSUE TITLE
Clean build of v1.5.12 fails due to v8

### ISSUE THREAD

**Issue by KVeschgini** [timeplus-io/proton#793]
**What's wrong**
A clean build on M2 Mac using Docker fails due to v8.

**How to reproduce**

```
git clone --recurse-submodules git@github.com:timeplus-io/proton.git

cd proton

./docker/packager/packager --package-type binary --docker-image-version clang-16 --proton-build --enable-proton-local --output-dir `pwd`/build_output --compiler clang-16-darwin
```

**Error message**
Build fails with
```
ninja: error: 'contrib/v8-cmake/bytecode_builtins_list_generator', needed by 'contrib/v8-cmake/generated/builtins-generated/bytecodes-builtins-list.h', missing and no known rule to make it
```

**Comment by yokofly** [comment]
edit: add brew install 
I probably know something.. sorry about this.
the `--compiler clang-16-darwin` will jump to cross compile, 
[we hard code some build binary for the v8.](https://github.com/timeplus-io/proton/blob/4588e5c43c6dd39b2dde0d6944458f065f0ad60c/.github/workflows/release_build.yml#L258-L272)

would you like to use directly bare metal build instead of docker?
https://github.com/timeplus-io/proton/blob/develop/BUILD.md#bare-metal-build-5


the proton server final is a static library. **the fresh build basically need  about 90 minutes.**
also you can download the [binary](https://github.com/timeplus-io/proton/releases/tag/v1.5.12) or pull the [docker](https://github.com/timeplus-io/proton/pkgs/container/proton) or [brew install ](https://github.com/timeplus-io/homebrew-timeplus?tab=readme-ov-file#installation)directly to take a try proton.

**Comment by KVeschgini** [comment]
Thanks, I am aware that the binary exists and I am already using it. I am trying to build proton to be able to work on the source code. The build also fails under wsl and on a ubuntu machine. I will try again, document the process and then make a bug ticket.

**Comment by yokofly** [comment]
really appreciate your trial. I check the code again,  the "docker build for macOS" issue may not have a quick fix. 
Would you mind trying the bare-metal build instead? the macOS use the dockered low level is based on arm/x86 linux.

Regarding the WSL / Ubuntu build failure, this seems to be an issue. 
Some of our colleagues already use WSL for their daily development and debugging.

**Comment by KVeschgini** [comment]
Bare-metal build worked for me after upgrading xcode to version 15.4.

**Comment by yokofly** [comment]
glad to hear that. There's a current issue with macOS where the stacktrace only works in debug mode, but there's no stacktrace when you throw an exception directly (ClickHouse already has a patch to fix this, but I don't have the time to back port it).

Apart from this problem, macOS also doesn't have jemalloc && sanitizer. thoes are some potential issues we currently encountered.
